## NumPy

In [2]:
from numpy import *

In [3]:
arr = array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [4]:
# Numpy Array : adding a scalar to a Numpy Array
arr = array([1, 2, 3, 4, 5])
print(arr + 5)


[ 6  7  8  9 10]


In [5]:
# matrix addition
arr1 = array([[1, 2], [3, 4]])
arr2 = array([[5, 6], [7, 8]])
print(arr1 + arr2)

[[ 6  8]
 [10 12]]
